import type { StyleConfig, StyleName } from '../types';

export const STYLE_CONFIG: Record<StyleName, StyleConfig> = {
  gemini: {
    logo: 'FindDeep',
    title: 'FindDeep',
    placeholder: '问问 FindDeep',
    disclaimer: 'FindDeep 是一款内部协作工具，信息仅供参考。',
    modelLabel: 'Gemini Advanced',
    welcomeTitle: '你好呀',
    welcomeSubtitle: '有什么我可以帮忙的吗？',
    favicon: 'fd-sparkle',
    uiName: 'Gemini',
    dotBg: 'linear-gradient(135deg, #4285f4, #d96570)'
  },
  chatgpt: {
    logo: 'ChatGPT',
    title: 'ChatGPT',
    placeholder: 'Message ChatGPT...',
    disclaimer: 'ChatGPT can make mistakes. Consider verifying important information.',
    modelLabel: 'GPT-4',
    welcomeTitle: 'How can I help you today?',
    welcomeSubtitle: "I'm ChatGPT, here to chat with you.",
    favicon: 'https://cdn.oaistatic.com/_next/static/media/favicon-32x32.630a2b99.png',
    uiName: 'ChatGPT',
    dotBg: 'linear-gradient(135deg, #10a37f, #1a7f64)'
  },
  mdn: {
    logo: 'MDN',
    title: 'MDN Web Docs',
    placeholder: 'Search MDN...',
    disclaimer: 'By developers, for developers.',
    modelLabel: 'MDN-AI',
    welcomeTitle: 'Resources for developers',
    welcomeSubtitle: 'Documenting web technologies',
    favicon: 'https://developer.mozilla.org/favicon-48x48.cbbd161b.png',
    uiName: 'MDN',
    dotBg: 'linear-gradient(135deg, #15141A, #555555)',
    isBeta: true
  },
  vscode: {
    logo: 'VS Code',
    title: 'Visual Studio Code',
    placeholder: 'Ask Copilot or type / for commands',
    disclaimer: 'AI-generated code may be incorrect. Please verify.',
    modelLabel: 'Copilot',
    welcomeTitle: 'Welcome to VS Code',
    welcomeSubtitle: 'Unlock the power of AI-assisted coding',
    favicon: 'https://code.visualstudio.com/favicon.ico',
    uiName: 'VS Code',
    dotBg: 'linear-gradient(135deg, #0066b8, #007acc)',
    isBeta: true
  },
  terminal: {
    logo: 'Terminal',
    title: 'root@linux:~',
    placeholder: 'root@linux:~# ',
    disclaimer: 'Warning: You are currently operating as root.',
    modelLabel: 'Root API',
    welcomeTitle: 'System Online',
    welcomeSubtitle: 'Linux version 5.15.0-101-generic',
    favicon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Terminal_icon_%28macOS%29.svg/120px-Terminal_icon_%28macOS%29.svg.png',
    uiName: 'Terminal',
    dotBg: 'linear-gradient(135deg, #000000, #16c60c)',
    isBeta: true
  },
  idea: {
    logo: 'IntelliJ IDEA',
    title: 'IntelliJ IDEA',
    placeholder: 'Ask AI Assistant...',
    disclaimer: 'AI Assistant can make mistakes. Please check the suggestions.',
    modelLabel: 'AI Assistant',
    welcomeTitle: 'Hello User',
    welcomeSubtitle: 'How can I help you write better code today?',
    favicon: 'https://resources.jetbrains.com/storage/products/intellij-idea/img/meta/intellij-idea_logo_300x300.png',
    uiName: 'IDEA',
    dotBg: 'linear-gradient(135deg, #fe2857, #087cfa)',
    isBeta: true
  },
  webstorm: {
    logo: 'WebStorm',
    title: 'WebStorm',
    placeholder: 'Ask AI Assistant...',
    disclaimer: 'AI Assistant can make mistakes. Please check the suggestions.',
    modelLabel: 'AI Assistant',
    welcomeTitle: 'Hello Web Developer',
    welcomeSubtitle: 'Let\'s write some JavaScript today',
    favicon: 'https://resources.jetbrains.com/storage/products/webstorm/img/meta/webstorm_logo_300x300.png',
    uiName: 'WebStorm',
    dotBg: 'linear-gradient(135deg, #00cdba, #087cfa)',
    isBeta: true
  },
  wiki: {
    logo: 'Wikipedia',
    title: '公司内网 Wiki',
    placeholder: 'Search Wiki...',
    disclaimer: '内容由全体员工共同维护。',
    modelLabel: 'WikiBot',
    welcomeTitle: '企业知识库',
    welcomeSubtitle: '欢迎贡献词条和内容',
    favicon: '',
    uiName: 'WiKi',
    dotBg: 'linear-gradient(135deg, #BEBEBE, #4B4B4B)',
    isBeta: true
  },
    stackoverflow: {
    logo: 'Stack Overflow',
    title: 'Stack Overflow',
    placeholder: 'Search for questions...',
    disclaimer: 'Answers are provided by the community.',
    modelLabel: 'OverflowAI',
    welcomeTitle: 'Every developer has a tab open to Stack Overflow',
    welcomeSubtitle: 'Where developers learn, share, and build careers.',
    favicon: 'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png',
    uiName: 'Stack Overflow',
    dotBg: 'linear-gradient(135deg, #F48024, #D66D14)',
    isBeta: true
  },
  juejin: {
    logo: '稀土掘金',
    title: 'IT技术社区',
    placeholder: '搜索前端、后端、架构...',
    disclaimer: '掘金文章和评论均由用户提供，请注意甄别信息的准确性',
    modelLabel: '掘金酱',
    welcomeTitle: '掘金一下',
    welcomeSubtitle: '发现全网优质技术内容',
    favicon: 'https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web/e08da34488b114bd4c665ba2fa520a31.svg',
    uiName: 'IT技术社区',
    dotBg: 'linear-gradient(135deg, #1E80FF, #005ce6)',
    isBeta: true
  },
  classic_doc1: {
    logo: '研发文档',
    title: '开发指南',
    placeholder: '搜索文档内容...',
    disclaimer: '内部研发文档库，受保密协议保护。',
    modelLabel: 'DocSense',
    welcomeTitle: '文档中心',
    welcomeSubtitle: '请查阅相关规范和指引',
    favicon: '',
    uiName: '经典文档1',
    dotBg: 'linear-gradient(135deg, #2b5876, #4e4376)',
    isBeta: true
  },
  classic_doc2: {
    logo: '设计规范',
    title: 'UI Design System',
    placeholder: '搜索组件及规范...',
    disclaimer: '所有设计产物均属公司资产，请勿外传。',
    modelLabel: 'DesignAI',
    welcomeTitle: '探索设计系统',
    welcomeSubtitle: '构建统一的用户体验',
    favicon: '',
    uiName: '经典文档2',
    dotBg: 'linear-gradient(135deg, #614385, #516395)',
    isBeta: true
  },
  classic_doc3: {
    logo: '架构分析',
    title: '系统架构详解',
    placeholder: '搜索架构白皮书...',
    disclaimer: '核心业务文档，请妥善保管。',
    modelLabel: 'ArchBot',
    welcomeTitle: '系统架构图',
    welcomeSubtitle: '掌握底层核心逻辑',
    favicon: '',
    uiName: '经典文档3',
    dotBg: 'linear-gradient(135deg, #1e3c72, #2a5298)',
    isBeta: true
  },
  classic_blog1: {
    logo: '张三的技术专栏',
    title: 'Tech Blog',
    placeholder: '搜索博文内容...',
    disclaimer: '文章均为个人观点，与公司立场无关。',
    modelLabel: 'BlogAI',
    welcomeTitle: '最新博文流',
    welcomeSubtitle: '记录技术的点点滴滴',
    favicon: '',
    uiName: '经典博客1',
    dotBg: 'linear-gradient(135deg, #cc2b5e, #753a88)',
    isBeta: true
  },
  classic_blog2: {
    logo: '李四的随笔',
    title: 'Thoughts',
    placeholder: '查找读书笔记与随写...',
    disclaimer: '仅供互相学习交流使用。',
    modelLabel: 'ThoughtBot',
    welcomeTitle: '读书笔记',
    welcomeSubtitle: '分享每一次思想的碰撞',
    favicon: '',
    uiName: '经典博客2',
    dotBg: 'linear-gradient(135deg, #42275a, #734b6d)',
    isBeta: true
  }
};
