import type { StyleConfig, StyleName } from '../types'

export const STYLE_CONFIG: Record<StyleName, StyleConfig> = {
  gemini: {
    logo: 'FindDeep',
    title: 'FindDeep',
    placeholder: '问问 FindDeep',
    disclaimer: 'FindDeep 是一款内部协作工具，信息仅供参考。',
    modelLabel: 'Gemini Advanced',
    welcomeTitle: '你好呀',
    welcomeSubtitle: '有什么我可以帮忙的吗？',
    favicon: 'fd-sparkle',
    uiName: 'Gemini',
    dotBg: 'linear-gradient(135deg, #4285f4, #d96570)'
  },
  chatgpt: {
    logo: 'ChatGPT',
    title: 'ChatGPT',
    placeholder: 'Message ChatGPT...',
    disclaimer: 'ChatGPT can make mistakes. Consider verifying important information.',
    modelLabel: 'GPT-4',
    welcomeTitle: 'How can I help you today?',
    welcomeSubtitle: "I'm ChatGPT, here to chat with you.",
    favicon: 'https://cdn.oaistatic.com/_next/static/media/favicon-32x32.630a2b99.png',
    uiName: 'ChatGPT',
    dotBg: 'linear-gradient(135deg, #10a37f, #1a7f64)'
  },
  classic_blog1: {
    logo: '张三的技术专栏',
    title: 'Tech Blog',
    placeholder: '搜索博文内容...',
    disclaimer: '文章均为个人观点，与公司立场无关。',
    modelLabel: 'BlogAI',
    welcomeTitle: '最新博文流',
    welcomeSubtitle: '记录技术的点点滴滴',
    favicon: '',
    uiName: '经典博客-α',
    dotBg: 'linear-gradient(135deg, #cc2b5e, #753a88)',
    isBeta: true,
    betaText: '限免',
    tagType: 'free'
  },
  classic_blog2: {
    logo: '李四的随笔',
    title: 'Thoughts',
    placeholder: '查找读书笔记与随写...',
    disclaimer: '仅供互相学习交流使用。',
    modelLabel: 'ThoughtBot',
    welcomeTitle: '读书笔记',
    welcomeSubtitle: '分享每一次思想的碰撞',
    favicon: '',
    uiName: '经典博客-β',
    dotBg: 'linear-gradient(135deg, #42275a, #734b6d)',
    isBeta: true
  },
  classic_blog3: {
    logo: '王五的成长空间',
    title: 'Daily Logs',
    placeholder: '记录每一天的进步...',
    disclaimer: '勤学如春起之苗，不见其增，日有所长。',
    modelLabel: 'GrowthAI',
    welcomeTitle: '成长记录',
    welcomeSubtitle: '沉淀技术，感悟生活',
    favicon: '',
    uiName: '经典博客-γ',
    dotBg: 'linear-gradient(135deg, #3f2b96, #a8c0ff)',
    isBeta: true
  },
  classic_doc1: {
    logo: '研发文档',
    title: '开发指南',
    placeholder: '搜索文档内容...',
    disclaimer: '内部研发文档库，受保密协议保护。',
    modelLabel: 'DocSense',
    welcomeTitle: '文档中心',
    welcomeSubtitle: '请查阅相关规范和指引',
    favicon: '',
    uiName: '经典文档-α',
    dotBg: 'linear-gradient(135deg, #2b5876, #4e4376)',
    isBeta: true,
    betaText: '限免',
    tagType: 'free'
  },
  classic_doc2: {
    logo: '设计规范',
    title: 'UI Design System',
    placeholder: '搜索组件及规范...',
    disclaimer: '所有设计产物均属公司资产，请勿外传。',
    modelLabel: 'DesignAI',
    welcomeTitle: '探索设计系统',
    welcomeSubtitle: '构建统一的用户体验',
    favicon: '',
    uiName: '经典文档-β',
    dotBg: 'linear-gradient(135deg, #614385, #516395)',
    isBeta: true
  },
  classic_doc3: {
    logo: '核心技术文档',
    title: 'Internal Wiki',
    placeholder: '搜索技术白皮书...',
    disclaimer: '核心业务资产，请严格遵守安全审计规范。',
    modelLabel: 'CoreBot',
    welcomeTitle: '技术中台文档',
    welcomeSubtitle: '掌握全栈核心架构逻辑',
    favicon: '',
    uiName: '经典文档-γ',
    dotBg: 'linear-gradient(135deg, #0f2027, #203a43, #2c5364)',
    isBeta: true
  },
  mdn: {
    logo: 'MDN',
    title: 'MDN Web Docs',
    placeholder: 'Search MDN...',
    disclaimer: 'By developers, for developers.',
    modelLabel: 'MDN-AI',
    welcomeTitle: 'Resources for developers',
    welcomeSubtitle: 'Documenting web technologies',
    favicon: 'https://developer.mozilla.org/favicon-48x48.cbbd161b.png',
    uiName: 'MDN',
    dotBg: 'linear-gradient(135deg, #15141A, #555555)',
    isBeta: true
  },
  wiki: {
    logo: 'Wikipedia',
    title: '公司内网 Wiki',
    placeholder: 'Search Wiki...',
    disclaimer: '内容由全体员工共同维护。',
    modelLabel: 'WikiBot',
    welcomeTitle: '企业知识库',
    welcomeSubtitle: '欢迎贡献词条和内容',
    favicon: '',
    uiName: 'WiKi',
    dotBg: 'linear-gradient(135deg, #BEBEBE, #4B4B4B)',
    isBeta: true
  },
  stackoverflow: {
    logo: 'Stack Overflow',
    title: 'Stack Overflow',
    placeholder: 'Search for questions...',
    disclaimer: 'Answers are provided by the community.',
    modelLabel: 'OverflowAI',
    welcomeTitle: 'Every developer has a tab open to Stack Overflow',
    welcomeSubtitle: 'Where developers learn, share, and build careers.',
    favicon: 'https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png',
    uiName: 'Stack Overflow',
    dotBg: 'linear-gradient(135deg, #F48024, #D66D14)',
    isBeta: true
  },
  juejin: {
    logo: 'IT技术社区',
    title: 'IT技术社区',
    placeholder: '搜索前端、后端、架构...',
    disclaimer: 'IT文章和评论均由用户提供，请注意甄别信息的准确性',
    modelLabel: 'IT酱',
    welcomeTitle: 'IT一下',
    welcomeSubtitle: '发现全网优质技术内容',
    favicon: '',
    uiName: 'IT技术社区',
    dotBg: 'linear-gradient(135deg, #1E80FF, #005ce6)',
    isBeta: true
  }
  // vscode: {
  //   logo: 'VS Code',
  //   title: 'Visual Studio Code',
  //   placeholder: 'Ask Copilot or type / for commands',
  //   disclaimer: 'AI-generated code may be incorrect. Please verify.',
  //   modelLabel: 'Copilot',
  //   welcomeTitle: 'Welcome to VS Code',
  //   welcomeSubtitle: 'Unlock the power of AI-assisted coding',
  //   favicon: 'https://code.visualstudio.com/favicon.ico',
  //   uiName: 'VS Code',
  //   dotBg: 'linear-gradient(135deg, #0066b8, #007acc)',
  //   isBeta: true
  // },
  // terminal: {
  //   logo: 'Terminal',
  //   title: 'root@linux:~',
  //   placeholder: 'root@linux:~# ',
  //   disclaimer: 'Warning: You are currently operating as root.',
  //   modelLabel: 'Root API',
  //   welcomeTitle: 'System Online',
  //   welcomeSubtitle: 'Linux version 5.15.0-101-generic',
  //   favicon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Terminal_icon_%28macOS%29.svg/120px-Terminal_icon_%28macOS%29.svg.png',
  //   uiName: 'Terminal',
  //   dotBg: 'linear-gradient(135deg, #000000, #16c60c)',
  //   isBeta: true
  // },
  // idea: {
  //   logo: 'IntelliJ IDEA',
  //   title: 'IntelliJ IDEA',
  //   placeholder: 'Ask AI Assistant...',
  //   disclaimer: 'AI Assistant can make mistakes. Please check the suggestions.',
  //   modelLabel: 'AI Assistant',
  //   welcomeTitle: 'Hello User',
  //   welcomeSubtitle: 'How can I help you write better code today?',
  //   favicon: 'https://resources.jetbrains.com/storage/products/intellij-idea/img/meta/intellij-idea_logo_300x300.png',
  //   uiName: 'IDEA',
  //   dotBg: 'linear-gradient(135deg, #fe2857, #087cfa)',
  //   isBeta: true
  // },
  // webstorm: {
  //   logo: 'WebStorm',
  //   title: 'WebStorm',
  //   placeholder: 'Ask AI Assistant...',
  //   disclaimer: 'AI Assistant can make mistakes. Please check the suggestions.',
  //   modelLabel: 'AI Assistant',
  //   welcomeTitle: 'Hello Web Developer',
  //   welcomeSubtitle: 'Let\'s write some JavaScript today',
  //   favicon: 'https://resources.jetbrains.com/storage/products/webstorm/img/meta/webstorm_logo_300x300.png',
  //   uiName: 'WebStorm',
  //   dotBg: 'linear-gradient(135deg, #00cdba, #087cfa)',
  //   isBeta: true
  // }
}
